### ISSUE TITLE
link on back class

### ISSUE THREAD

**Issue by nordbit** [nnattawat/flip#4]
Links  on div with "back" class not working.

**Comment by nnattawat** [comment]
@dancaron is the problem only on firefox?

**Comment by dancaron** [comment]
@nnattawat - no, was having the issue in chrome

**Comment by toel--** [comment]
Got the same issue as reported by @dancaron: changing to 
var direction = settings.reverse? "-179deg" : "179deg";
avoids the problem and the missing one degree is barely noticeable.

**Comment by nnattawat** [comment]
I have pushed the new code that might fix the problem.

**Comment by toel--** [comment]
Sorry no, problem still there and now affects firefox css 'center'.
I created a JSFiddle, so you may see my setup: http://jsfiddle.net/toel/373pxccj/2/

**Comment by nnattawat** [comment]
I closed this issue as it was duplicated with the #8
