### ISSUE TITLE
Display issues on different browsers

### ISSUE THREAD

**Issue by sixtyseven-multimedia** [nnattawat/flip#8]
In Safari (iOS and windows checked), when front is flipped, the contend is not hidden.

In Opera on windows, the back content is in front and no flipping happens.

On IE11, the front is flipped, but no back is revealed. When clicking again, the content is more or less "flipped" back, but the card rotates weird.

Any ideas about that?

**Comment by iMuzz** [comment]
I'm experiencing the same issue(Safari back content not hiding on flip). Were you able to figure out a fix for this issue? 

Followed.

**Comment by redrick** [comment]
Hey guys, I created a PR if you still care for it :) 

https://github.com/nnattawat/flip/pull/9

**Comment by Download** [comment]
This issue seems to have been solved. If not, please create a repro (using e.g. JS Fiddle) with v1.0.12 of Flip and re-open this issue (or create a new one).

**Comment by marko59** [comment]
This is still an issue on IOS Safari with X axis set. Flip works fine with Y axis set.

**Comment by Download** [comment]
Reopened, but please provide more info. Do you have a repro we can check?
